In [2]:
import numpy as np

data = np.array(np.random.randint(1, 100, size=25)).reshape(5,5)
print(data)

[[93 11 59 86 11]
 [ 3 59 92 57 73]
 [12  7  4 94 71]
 [62 33 91 87 54]
 [ 6 83 33 12 86]]


In [3]:
# Matrix manipulation - Swap the second and fourth rows of the data matrix.

data[[1,3]] = data[[3,1]]
print(data)

[[93 11 59 86 11]
 [62 33 91 87 54]
 [12  7  4 94 71]
 [ 3 59 92 57 73]
 [ 6 83 33 12 86]]


In [4]:
normalized_data = (data - np.min(data)) / (np.max(data) - np.min(data))
print(normalized_data)

[[0.98901099 0.08791209 0.61538462 0.91208791 0.08791209]
 [0.64835165 0.32967033 0.96703297 0.92307692 0.56043956]
 [0.0989011  0.04395604 0.01098901 1.         0.74725275]
 [0.         0.61538462 0.97802198 0.59340659 0.76923077]
 [0.03296703 0.87912088 0.32967033 0.0989011  0.91208791]]


In [5]:
z_score_data = (data - np.mean(data)) / np.std(data)
print(z_score_data)

[[ 1.2456495  -1.19563298  0.23341042  1.03724733 -1.19563298]
 [ 0.32272563 -0.54065475  1.18610602  1.06701907  0.08455173]
 [-1.16586124 -1.31471993 -1.40403514  1.27542123  0.59067127]
 [-1.43380688  0.23341042  1.21587776  0.17386695  0.65021475]
 [-1.34449166  0.94793212 -0.54065475 -1.16586124  1.03724733]]


In [7]:
# Array splitting - Reshape the data matrix into a vector (Hint: use np.ravel) and split this array into five equal-sized sub-arrays.

array = np.ravel(data)
print(array)

[93 11 59 86 11 62 33 91 87 54 12  7  4 94 71  3 59 92 57 73  6 83 33 12
 86]


In [9]:
matrix = np.reshape(array, (5,5))
print(matrix)

[[93 11 59 86 11]
 [62 33 91 87 54]
 [12  7  4 94 71]
 [ 3 59 92 57 73]
 [ 6 83 33 12 86]]


In [12]:
# Dot product - Create two vectors of size 5 with any values. Compute the dot product of the two vectors*.

a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

print(np.dot(a,b))

70


In [17]:
# Matrix multiplication - Create another 3x3 matrix with any values (let’s call it data2). Perform matrix multiplication (dot product of data (first 3x3 part) and data2).

data2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(np.dot(data[:3, :3], data2))

[[ 550  713  876]
 [ 831 1017 1203]
 [  68   91  114]]


In [21]:
# Inverse of a matrix - Create a 3x3 identity matrix*, multiply it with 2 and compute its inverse.

a = np.eye(3)
b = a*2
c = np.linalg.inv(b)
print(c)


[[0.5 0.  0. ]
 [0.  0.5 0. ]
 [0.  0.  0.5]]


In [22]:
# Eigenvalues and eigenvectors - For the first 3x3 part of the data matrix, compute the eigenvalues and eigenvectors*.

matrix = data[:3, :3]
print(np.linalg.eig(matrix))

(array([113.65371953,  27.63119248, -11.28491201]), array([[ 0.71546464,  0.2835184 , -0.22329601],
       [ 0.68787732, -0.94910557, -0.80794025],
       [ 0.12220942, -0.13717116,  0.54531775]]))


In [ ]:
# I didn't get these tasks:

# Find missing values - Replace random 5 elements in the data matrix with np.nan. Find the indices of the missing values.
# Replace missing values - Replace the missing values in the data matrix with the mean of the matrix (ignoring the missing values while computing the mean).