In [6]:
import numpy as np

# Create a 3x3x3 array with random values using np.random.random().

arr = np.random.random((3,3))
print(arr)

[[0.33366994 0.31636476 0.87521694]
 [0.89350991 0.23292505 0.00779559]
 [0.61610102 0.37918414 0.34153234]]


In [9]:
# Create a 10x10 array with random values and find the minimum and maximum values.

arr = np.random.random((10,10))
print(np.max(arr))
print(np.min(arr))

0.9985444508910611
0.01118577159627332


In [13]:
# Create a random vector of size 30 and find the mean* value.

arr = np.array(np.random.randint(100,size = 30))
print(np.mean(arr))

53.56666666666667


In [19]:
arr = np.ones((5,5))

arr[1:4, 1:4] = 0
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [28]:
arr = np.ones((3,3))
arr2 = np.pad(arr, (1, 1), 'constant', constant_values=(0))
print(arr2)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [38]:
# Replace all odd numbers in an array with -1 without changing the original array.

arr = np.arange(10)
print(arr)

for index, num in enumerate(arr):
    if num % 2 != 0:
        arr[index] = -1
    
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [48]:
# Create a 5x5 matrix with values 1,2,3,4,7 on the diagonal* using np.diag.

arr = np.diag([1, 2, 3, 4, 7])
print(arr)



[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 7]]


In [60]:
# Create a 8x8 matrix and fill it with a checkerboard pattern using slicing*.

arr = np.zeros((8,8))
arr[1::2,::2] = 1
arr[::2, 1::2] = 1
print(arr)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [61]:
# Given a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? Use np.unravel_index.

print(np.unravel_index([99], (6,7,8)))

(array([1], dtype=int64), array([5], dtype=int64), array([3], dtype=int64))


In [63]:
# Normalize* a 5x5 random matrix. The normalization formula is (matrix - matrix.min()) / (matrix.max() - matrix.min()).

matrix = np.random.random((5,5))
arr = (matrix - matrix.min()) / (matrix.max() - matrix.min())
print(matrix)
print(arr)

[[0.5967873  0.66683384 0.26429726 0.67992847 0.5231299 ]
 [0.05209547 0.38170367 0.00412232 0.32146975 0.6086236 ]
 [0.60368825 0.2034344  0.28934615 0.96556022 0.16905225]
 [0.09613549 0.85029992 0.28448025 0.78010965 0.1519297 ]
 [0.17407305 0.88804917 0.42033198 0.60187811 0.1357344 ]]
[[0.61643605 0.68929207 0.27061023 0.70291191 0.53982434]
 [0.04989729 0.39272568 0.         0.33007585 0.62874709]
 [0.62361378 0.20730624 0.29666381 1.         0.17154506]
 [0.09570371 0.88011675 0.29160274 0.80711124 0.15373576]
 [0.17676724 0.91938008 0.43290332 0.62173104 0.13689088]]


In [76]:
# Given a two-dimensional array, extract unique rows. You can use np.unique with the axis argument.

arr = np.array([['a', 'b', 'b', 'c', 'a'], ['a', 'b', 'b', 'c', 'a']])

a = np.unique(arr, axis = 1)
print(a)

[['a' 'b' 'c']
 ['a' 'b' 'c']]


In [77]:
# Create a structured array* representing a position (x,y) and a color (r,g,b). Use np.dtype to create a custom dtype for this task.

arr = np.zeros((3,), dtype=[('x', 'float'), ('y', 'float'),
       ('r', 'int'), ('g', 'int'), ('b','int')])
       
arr['x'] = np.random.rand(3)
arr['y'] = np.random.rand(3)
arr['r'] = np.random.randint(0, 255, 3)
arr['g'] = np.random.randint(0, 255, 3)
arr['b'] = np.random.randint(0, 255, 3)

print(arr)

[(0.68310893, 0.43430922, 118,  27, 239)
 (0.15749253, 0.96825376,  40, 138, 110)
 (0.50373752, 0.69418396, 245, 132, 203)]


In [ ]:
# How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? Use np.add.at. This method performs unbuffered* in place operation on operand ‘a’ for elements specified by ‘indices’.

# Considering a four dimensions array, how to get sum over the last two axis at once? Use np.sum with axis=(-2,-1).

# Example output: The sum of the elements over the last two axes.

# How to get the diagonal of a dot product? Use np.diag and np.dot.

# Example output: This command calculates the dot product of two arrays and then extracts the diagonal elements.


# Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? This involves use of np.zeros and array indexing.

# Example output:

# [1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5]

# How to compute averages using a sliding window over an array? This involves some manipulation of array indexing and arithmetic operations. Essentially, you would compute a cumulative sum* and then subtract the sum at the beginning of the window from each element.


# Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution* with n degrees, i.e., the rows which only contain integers and which sum to n. This involves understanding of multinomial distribution.


# Compute bootstrapped 95% confidence intervals* for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). Use np.percentile.

# Example output: Two numbers representing the lower and upper bound of the confidence interval.