In [1]:
import numpy as np

# Create a vector* of zeros with size 10 using np.zeros().

vector = np.zeros(10)
# print(vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
# Compute the memory size* of any array. Note: You can do this by multiplying the length of the array by the size of one array element, which you can find using the .itemsize attribute.

vector_size = vector.itemsize * len(vector)

In [5]:
# print(vector_size)

80


In [8]:
# Retrieve the documentation of the numpy add function from the command line.

help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

In [10]:
# Create a vector with values ranging from 10 to 49 using np.arange()

array = np.arange(10, 50)

# Reverse a vector so the first element becomes last (Hint: Use slicing).

array_rev = array[::-1]

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [11]:
# Create a 3x3 matrix* with values ranging from 0 to 8 using np.reshape().

array = np.arange(9)
matrix = np.reshape(array, (3,3))
# print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [12]:
# Find indices of non-zero elements from [1,2,0,0,4,0] using np.nonzero().

array = [1,2,0,0,4,0]
print(np.nonzero(array))

(array([0, 1, 4], dtype=int64),)


In [13]:
# Create a 3x3 identity matrix* using np.eye().

array = np.eye(3)
print(array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
# Create a 5x5 matrix with row values ranging from 0 to 4. The output should be a matrix where each row is [0, 1, 2, 3, 4].
matrix = np.zeros((5,5))
matrix += np.arange(5)
print(matrix)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [29]:
# Create a vector of size 10 with values ranging from 0 to 1, both excluded. You can use np.linspace.

arrow = np.linspace(0, 1, 12)[1:-1]
print(arrow)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [33]:
# Create a random vector of size 10 and sort it.

array = np.random.rand(10)
print(np.sort(array))



[0.03210111 0.04738837 0.18936435 0.22793855 0.25483591 0.25767998
 0.34287937 0.58276539 0.68552544 0.71777581]


In [41]:
# Print the minimum and maximum representable value for each numpy scalar type* (int8, int32, int64, float32, float64). Use np.iinfo and np.finfo.

a = np.iinfo(np.int8)
b = np.iinfo(np.int32)
c = np.iinfo(np.int64)
print(a.min, b.min, c.min)
print(a.max, b.max, c.max)

a = np.finfo(np.float32)
b = np.finfo(np.float64)
print(a.min, b.min)
print(a.max, b.max)

-128 -2147483648 -9223372036854775808
127 2147483647 9223372036854775807
-3.4028235e+38 -1.7976931348623157e+308
3.4028235e+38 1.7976931348623157e+308


In [50]:
# How to convert a float (32 bits) array into an integer (32 bits) in place? Use np.ndarray.astype.

a = np.array([1.0], dtype="float32")
b = a.astype('int')
print(a.dtype)
print(b.dtype)


float32
int32


In [54]:
# Subtract the mean* of each row of a matrix. Use np.mean with axis=1.

array = np.arange(9)
matrix = np.reshape(array, (3,3))

matrix_mean = matrix.mean(axis=1, keepdims=True)
print(matrix_mean)

[[1.]
 [4.]
 [7.]]


In [56]:
# How to sort an array by the nth column? Use np.argsort.

matrix = np.array([[4, 2, 3], [6, 1, 5], [7, 9, 8]])
sorted_matrix = matrix[matrix[:,1].argsort()]
print(sorted_matrix)

[[6 1 5]
 [4 2 3]
 [7 9 8]]


In [60]:
# How to swap two rows of an array? You can do this using array indexing.

matrix = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
matrix[[0, 1]] = matrix[[1, 0]]
print(matrix)

[[3 4 5]
 [0 1 2]
 [6 7 8]]


In [62]:
# Given an array C that is a bincount*, how to produce an array A such that np.bincount(A) == C? Use np.repeat.

a = np.array([2, 2, 1, 1, 1, 0, 0, 0, 3, 3])
c = np.bincount(a)
recreated_array = np.repeat(np.arange(len(c)), c)
print(recreated_array)

[0 0 0 1 1 1 2 2 3 3]
